### PR TITLE
TINY-10804: add math-equation icon

### PR DESCRIPTION
**Pull request by lorenzo-pomili**
Related Ticket: TINY-10804

Description of Changes:

Pre-checks:
* [x] Changelog entry added
* [x] ~Tests have been added (if applicable)~
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

### CODE REVIEW

**Review by spocke — APPROVED** [review]
I think we add changelog items when adding icons.

**Comment by lorenzo-pomili** [comment]
> I think we add changelog items when adding icons.

under what project:
Screenshot from 2024-04-16 15-22-29

**Comment by spocke** [comment]
> > I think we add changelog items when adding icons.
> 
> under what project? 

Under the tinymce project check the existing changelog.md for similar entries. There are a few under the added sections.

**Review by TheSpyder — APPROVED** [review]

**Comment by TheSpyder** [comment]
We didn't used to, but a few snuck in without me realising. I try to avoid mentioning premium things in the core changelog.

**Pull request merged**
