### PR TITLE
Accessibility changes

### PR DESCRIPTION
**Pull request by danchr**
This push request address numerous small issues found during an accessibility audit.

### CODE REVIEW

**Comment by spocke** [comment]
Hmm. The aria-labelledby fixes are to workaround a IE 8 issue where Jaws wouldn't read the contents due to some internal bug. But I guess the amount users with Screen Readers and IE 8 is way way less than 1% of the user base. Will look into these changes, might take a while since I need to verify them on a few combinations of screen readers and browsers.

**Comment by danchr** [comment]
Hmm, I'm not quite done yet, so perhaps I was a bit too hasty in posting this… Thanks for the quick response, though! I'll let you know once it's done. Which combinations do you usually test in?

FWIW these are the issues the tester identified:

> 1. Editor: Toolbar buttons have bad aria-labelledby
> 5. Editor: Controls in Insert Link and Insert Table should have role of "combobox"
> 10. Editor: Insert Link has wrong value for "aria-describedby"
> 12. Editor: toolbar does not indicate focus
> 13. Editor: color menus lack focus border
> 15: Editor: color menus have bad label IDs
> 17. Editor: URL field has bad label ID
> 19. Editor: IFRAME title has bad info
> 20. Editor: Esc to close popup also (or only) closes compose
> 24. Editor: Insert Link and Insert Table cannot be reached via tabbing

**Comment by danchr** [comment]
I'll repost it once I'm done!

**Comment by spocke** [comment]
I works best with NVA and Firefox http://www.nvaccess.org/ but I also tested it on Jaws 6 when I did my last review. IE 8 with Jaws was causing all kinds of pain therefor the hacks around aria-labeledby to the same ID etc. I tend to run the screen readers in a VM since Jaws on tends to crash a lot. Haven't tested it on ChromeVox though.

**Pull request closed without merging**
