### PR TITLE
Tinymce: Validates the real existence of an uploaded image

### PR DESCRIPTION
**Pull request by guido-warken**
Related Ticket:

Description of Changes:
* When an image is uploaded actualy, a success callback is executed, even if an invalid image have been chosen through the file input of operating system

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

### CODE REVIEW

**Comment by metricjs** [comment]
Hi @guido-warken, thanks for this PR. Unfortunately we can not accept it in its current state. If you would like to continue with it, could you please:
- Describe a replication case for the issue you are trying to solve.
- Complete the checklist in the PR description by adding a changelog entry, tests, etc.
- Fix the linting issues that are causing the build to fail at the moment (and any other issues the build finds).

**Comment by guido-warken** [comment]
> Hi @guido-warken, thanks for this PR. Unfortunately we can not accept it in its current state. If you would like to continue with it, could you please:
> 
> * Describe a replication case for the issue you are trying to solve.
> * Complete the checklist in the PR description by adding a changelog entry, tests, etc.
> * Fix the linting issues that are causing the build to fail at the moment (and any other issues the build finds).

Hi, i am trying to run some tests, but i got this error:
Warning: Task "bedrock-auto:silver" not found. Used --force, continuing.
How can i solve it?

**Comment by metricjs** [comment]
Interesting error @guido-warken. What command did you run or steps did you follow to get that error? Were you following the contributing guide's [section about testing](https://github.com/tinymce/tinymce/blob/develop/CONTRIBUTING.md#testing)?

**Comment by lnewson** [comment]
As it's been over a month without any response, I'm going to close this sorry. If you'd still like to contribute this fix, please feel free to log a new PR when you're ready, though please be sure to include the details requested by @metricjs above.

**Pull request closed without merging**
