### PR TITLE
Add option to render HTML for autocomplete item

### PR DESCRIPTION
**Pull request by gzzo**
Currently the autocomplete can only render text or icons. This adds support to render arbitrary HTML.

### CODE REVIEW

**Comment by TheSpyder** [comment]
What's the use case here? This was a deliberate decision (dialog collections work the same way).

It's not quite as simple as this change, either, for example the `useText` boolean your change ignores is set in multi-column view where only icons are shown (no text). I'm wondering if something more along the lines of #4783 would help.

**Comment by gzzo** [comment]
I'm using my fork to render better items on mentions instead of just plain text:

Screen Shot 2019-07-02 at 11 19 53 AM

The autocompleter sets `useText` to `columns==1`, which is provided by the user of the autocompleter, so they are also indirectly providing `useText` as well.

**Comment by TheSpyder** [comment]
Ah, interesting. Yes I was trying to imply that `useText` is tied to the columns setting, but more specifically the effect of that is how does the component react if HTML is specified with multiple columns? That's where we might have to leave this until we've come up with a general collection grid solution via #4783.

**Comment by lofcz** [comment]
Any updates on this PR? This would be a really nice feature to have in core repo.

**Comment by TheSpyder** [comment]
We very deliberately only support text content in menus right now (for many reasons, such as highlighting the search term automatically instead of requiring integrators to do it).

I have raised this for discussion internally, we've been quite busy preparing for improved mobile support in the 5.1 release.

**Comment by gzzo** [comment]
You can see from my screenshot that highlighting still works, I didn't have to do anything special to make that work.

**Comment by TheSpyder** [comment]
> You can see from my screenshot that highlighting still works, I didn't have to do anything special to make that work.

That doesn't sound right, `replaceText` is the function that both enforces plain text and adds highlighting. It's not called with your changes if `spec.html` is used.

Our highlighting is based on plain text regex, so it's not appropriate for HTML highlighting (what if the search text matched a HTML tag name).

**Comment by gzzo** [comment]
I don't know what to tell you, you're obviously more familiar with this codebase, but highlighting works for free here. You can verify easily by cloning and building from this branch.

From what I can tell by looking at the DOM, there's two div wrappers on top of my `spec.html` content, the top most with `tox-collection__item tox-collection__item--active` (this one applies the highlight) classes its child with `tox-collection__item-label`. Only then is the custom html rendered.

**Comment by TheSpyder** [comment]
Maybe we're talking about different things? There are multiple meanings of the word highlight 🤔 

I'm talking about applying bold styling to the word `Jen` in `Jen User` of your screenshot. Not the tox active class which applies a background colour to the whole menu item.

**Comment by SimonFc** [comment]
The autocompleter is going to support a new "template" feature (targeted 5.6) which will make it possible to customize the autocompleter items. While arbitrary HTML wont be supported, the goal is to support the most common use cases, such as the example provided by gzzo.

**Comment by metricjs** [comment]
Thanks @gzzo for the PR. Since we are implementing similar functionality to be released in TinyMCE 5.6, I'm going to close this PR. If you have a chance to test out the new "template" feature in 5.6 when it's released, we would appreciate any feedback!

**Pull request closed without merging**
