### PR TITLE
Update theme.js

### PR DESCRIPTION
**Pull request by cclaerhout**
The "submit" event must be add to be sure the toolbar is hidden on submit (otherwise there's bug with the new table float toolbar).

### CODE REVIEW

**Comment by spocke** [comment]
Hmm. Not sure that it should hide it on submit. Could you tell me a bit more when this happens? Since a submit might potentially depending on integration not hide the editor.

**Comment by cclaerhout** [comment]
Hello Spocke,

When I send (submit) the message while the table is highlighted and the float table menu is displayed, everything works fine (the message is posted with ajax, so no refresh of the page), except that this float table menu is still displayed whereas it should be at least hidden if not removed.

I've implemented a workaround in my framework, so it's ok for me, but some users might get the same problem.

Cédric

**Comment by spocke** [comment]
The click on a submit button should produce a blur event and there for close the toolbar.

**Comment by cclaerhout** [comment]
It's strange, I've checked and to deal with the ajax call, there's an AutoValidationComplete which triggers the blur event. May be it's called to late. Any I've got a workaround, so it's ok.

**Pull request closed without merging**
