### PR TITLE
Fix "selection is null" issue on Firefox (#4015).

### PR DESCRIPTION
**Pull request by dbistriceanu**

### CODE REVIEW

**Comment by fyrkant** [comment]
@dbistriceanu 
Do you have an easy way to reproduce the problem? Can you create a [fiddle](http://fiddle.tinymce.com)?

**Comment by hmichal-dev** [comment]
@fyrkant I experience the same bug.

**Comment by fyrkant** [comment]
@hmichal-dev 
Ok, can you create a fiddle recreating it?

**Comment by fyrkant** [comment]
Directly when you lead the editor or do you have to something special to get the error?

**Comment by hmichal-dev** [comment]
I have the editor in Bootstrap Modal. Error message appears just after loading a site, before I open modal. When I put the code into fiddle (without modal, just textarea) there is not message in console.

Debug (with full, no minimized version) shows the error occurred in line related to this pull request

	// My code
	var fTags = {
	  'test': 'test',
	  'test2': 'test2'
	};
	$('textarea.tinymce-editable').each(function() {
	  var config = {
		selector: '#' + $(this).attr('id').toString(),
		menubar: false,
		toolbar: 'insert | mybutton | formatselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist | removeformat | code',
		plugins: [
		  'autolink lists link image charmap',
		  'code table contextmenu'
		],
		branding: false,
		setup: function(editor) {
		  var menuFields = [];
		  for (var tag in fTags) {
			var name = fTags[tag];
			menuFields.push({
			  text: name,
			  onclick: function(editor, fTag) {
				return function() {
				  var tag = fTag;
				  editor.insertContent(tag);
				};
			  }(editor, tag)
			});
		  }
		  editor.addButton('mybutton', {
			type: 'menubutton',
			text: 'Tagi',
			icon: false,
			menu: menuFields
		  });
		};
	  }
	  tinymce.init(config);
	});

**Comment by dbistriceanu** [comment]
The error only triggers in Firefox when it tries to interact with the editor but the element it's applied on is not yet in DOM (e.g. it's in a modal that is shown only on some action).
For example, you can see this on fiddle by forcing an auto_focus on init when the element is hidden:
http://fiddle.tinymce.com/0fgaab

**Comment by fyrkant** [comment]
@dbistriceanu 
Thank you for the fiddle! I just wanted a clear reproduction so I can try to make a test to fo with the fix.

**Comment by fyrkant** [comment]
This has been merged.

**Pull request closed without merging**
