### PR TITLE
Stop THEAD from inserting above CAPTION

### PR DESCRIPTION
**Pull request by WebVeteran**
When adding a thead check to see if a caption exists first, so that the caption is always the first child of the table.

### CODE REVIEW

**Comment by simonista** [comment]
Hey all, I'd love to see this pull request merged (see https://github.com/tinymce/tinymce/issues/3034 for a description of the spec).  Is there anything currently blocking this from getting merged?

**Comment by simonista** [comment]
Any chance we could get a response on this, even if it's "we're not going to accept this"?

**Comment by WebVeteran** [comment]
It's been 3 months. What's going on with this?

**Comment by bkirkby** [comment]
any word on this? i'd like to get this WebAIM compliant so i can use it. thanks!

**Comment by jayarjo** [comment]
This has been implemented.

**Pull request closed without merging**
