### PR TITLE
Addtooltipwithclassesforpathelement

### PR DESCRIPTION
**Pull request by catalinux**
fix eslint settings + add tooltip with classes for path

### CODE REVIEW

**Comment by catalinux** [comment]
Changed. Added that rule to eslint

**Comment by jayarjo** [comment]
What is the purpose of this one?

**Comment by catalinux** [comment]
To show classes of tags on mouse over the elemtns in the path .

Otherwhise, the user has to go in code to see if a class is applied to an element

**Comment by fyrkant** [comment]
The TinyMCE source code has been converted to TypeScript which makes this PR impossible to merge, so I am closing it. Please open up a new PR written in TypeScript if you want us to take a look at it again.

**Pull request closed without merging**
