### PR TITLE
TINY-10022: insert new block commands

### PR DESCRIPTION
**Pull request by vpyshnenko**
Related Ticket: TINY-10022

Description of Changes:
* Added two new commands for inserting new empty block before / after current position.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

### CODE REVIEW

**Review by TheSpyder — COMMENTED** [review]
I haven't had a chance to review it fully, but I will say - I was expecting what is now `NewBlock` to either use or refactor code from `InsertNewLine` and `InsertBlock` 🤔

**Comment by vpyshnenko** [comment]
@TheSpyder, the logic of these commands is way simpler. There is not much we need to reuse from `InsertNewLine`.  We don't need to delete the current ranged selection, choose linebreak/block,  inherit parent styles, or split the current block. In these commands, we want just to create an empty block before/after the current one.

**Review by TheSpyder — APPROVED** [review]
Ah I didn't look closely enough to see that `createNewBlock` had been refactored. Thank you for your patience.

**Review by TheSpyder — APPROVED** [review]
Ah I didn't look closely enough to see that `createNewBlock` had been refactored. Thank you for your patience.

**Pull request merged**
