### PR TITLE
Fix active state in context toolbar for link button

### PR DESCRIPTION
**Pull request by DoctorFTB**
Related Ticket:

Description of Changes:
* Fix active state in context toolbar for link button
Bug reproduce: https://fiddle.tiny.cloud/MDhaab/1

Pre-checks:
* [x] Changelog entry added
* [ ] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

### CODE REVIEW

**Comment by ashfordneil** [comment]
Hi @DoctorFTB,

Thanks for this contribution to TinyMCE, this looks like a really good start.

Before we can review this properly, can I get you to sign the CLA please? You should have received an email for this, but let me know if it hasn't come through.

**Comment by DoctorFTB** [comment]
> Hi @DoctorFTB,
> 
> Thanks for this contribution to TinyMCE, this looks like a really good start.
> 
> Before we can review this properly, can I get you to sign the CLA please? You should have received an email for this, but let me know if it hasn't come through.

Hey. Im sorry for late answer. I didnt get any email about CLA in my primary email, which connected to GitHub.

**Comment by metricjs** [comment]
Hey @DoctorFTB, we re-sent the CLA email yesterday. Hopefully it has come through this time. Please check your spam emails folder too - sometimes it ends up there.

**Comment by lnewson** [comment]
Hi @DoctorFTB,

As we haven't heard back from you in the last 2 weeks, we're going to close this PR as part of some house keeping. If you can sign the CLA we're happy to reopen this, otherwise for now we've logged an internal task to fix this issue.

Thanks again for raising this!

**Pull request closed without merging**
