### PR TITLE
Added support for the "img" and "iframe" tags' "loading" attribute

### PR DESCRIPTION
**Pull request by ataylor32**

### CODE REVIEW

**Comment by TheSpyder** [comment]
As far as I'm aware `loading` isn't a standard attribute on either of those tags?

**Comment by ataylor32** [comment]
@TheSpyder https://www.chromestatus.com/feature/5645767347798016

**Comment by lnewson** [comment]
As @TheSpyder mentioned this still only appears to be an experimental attribute and is mentioned it shouldn't be used in production on MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes As such including it in TinyMCE at this stage is a little bit premature.

**Comment by TheSpyder** [comment]
I think we can consider allowing experimental attributes, it encourages wider use and they won't harm browsers that don't support them. I'll open an internal discussion.

**Pull request merged**
