### PR TITLE
fix whiteSpaceRegExp so slow problem

### PR DESCRIPTION
**Pull request by bailnl**
hello

because this is real customer email, so i will take it replace to "w"（privacy policy）
the str length is 31754

image

chrome Version 66.0.3359.181 (Official Build) (64-bit)
Speed is as follows: 
image

Faster JavaScript Trim
http://blog.stevenlevithan.com/archives/faster-trim-javascript

by the way， should be abstracted into util methods

### CODE REVIEW

**Comment by alecpl** [comment]
What browser?

**Comment by bailnl** [comment]
@alecpl  chrome  Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by bailnl** [comment]
@alecpl http://blog.stevenlevithan.com/archives/faster-trim-javascript

**Comment by alecpl** [comment]
I can't reproduce the issue on the same Chromium version, nor Firefox. It's only 2 times slower, i.e. negligible. jQuery project uses similar single regexp. BTW, your second regexp is wrong.

**Comment by bailnl** [comment]
oh, no!.. wrong
i give you  test text

[test.txt](https://github.com/tinymce/tinymce/files/2071235/test.txt)

**Comment by fyrkant** [comment]
We haven't had any reports with the regexp being slow other than this and the blog post you're linking is 11 years old so I don't think it's applicable anymore.

**Pull request closed without merging**
