### PR TITLE
 Change "cmd" key check to "ctrl" key since only "ctrl" key is used for tab switches

### PR DESCRIPTION
**Pull request by SDemonUA**
**Before submitting a pull request** please do the following:

1. Fork [the repository](https://github.com/tinymce/tinymce) and create your branch from `master`
2. Have you added some code that should be tested? Write some tests! (Are you unsure how to write the test you want to write, ask us for help!)
3. Ensure that the tests pass: `grunt test`
4. Ensure that your code passes the linter: `grunt lint`
5. Make sure to sign the CLA.

### CODE REVIEW

**Comment by fyrkant** [comment]
That makes sense, but I still can't make the problem appear, do you have any way to reproduce it? It seems to indent lists as expected and switch tabs correctly even without your PR.

**Comment by SDemonUA** [comment]
We faced with this problem on MacOS. I do not have any mac to check, so I can't say was it Mozilla or Chrome

**Comment by fyrkant** [comment]
But do you have any steps on how you reproduced it? I'm trying putting my cursor inside a list and pressing CTRL+TAB and it seems to work as expected.

**Comment by SDemonUA** [comment]
[Firefox under Mac OS]
www.tinymce.com
create bullet or ordered list
add 2 items 
on last item press Ctrl+Tab
return to www.tinymce.com
last item would be indented to one more level
like : 
* Line one
    * Line two

**Comment by tinydylan** [comment]
Hi,

Apologies for the late reply. I have tested on FireFox and Chrome on Mac and am unable to reproduce the issue. We will be closing this PR for now. If the problem still exists, please feel free to let us know and we'll investigate further.

Many thanks.

**Pull request closed without merging**
