### PR TITLE
Add android constant to the tinymce.Env class

### PR DESCRIPTION
**Pull request by nhammadi**
Add android constant to the tinymce.Env class to detect if the current os is Android or not

### CODE REVIEW

**Comment by nhammadi** [comment]
Hey can Spocke, 
Can you please merge this pull request (or add the same feature in another way) in the next version (4.1.8)

Thanks

**Comment by spocke** [comment]
Just out of curiosity why do you need to sniff android? We might add it to core but if you can as easily detect android in your custom plugin it might be better to have it there.

**Comment by nhammadi** [comment]
Actually, I've already wrote that in a custom plugin but it will better to add that in the core Env object like you did to IOS and Mac.
And to answer your question about  why I need to sniff android ? I found out that there is a difference in the behaviour of google chrome Android and the IOS version so I need to fix them in my custom plugin

**Comment by spocke** [comment]
Added this thanks for the pull request.

**Pull request merged**
