### PR TITLE
Soft hypen

### PR DESCRIPTION
**Pull request by suit**
Added a new plugin for soft hyphens
Made additions to visualchars plugin to make them visible, just like nbsp

See http://en.wikipedia.org/wiki/Soft_hyphen for more info

Still missing: an icon for the button/menu entry

### CODE REVIEW

**Comment by spocke** [comment]
This is better of as a separate plugin. Closing.

**Comment by suit** [comment]
I don't see how this can solved via a plugin only without chaning the "core" - it needs changes in js/tinymce/plugins/visualchars/plugin.js to work, since it interferes with the functionality of the non breaking space (it does basically the same, but with another character).

since the functionalytic has a widespread use in modern responsive webdesigns (to control linebreaks in fluid layouts) it should be added to the core imho

**Comment by spocke** [comment]
Fixed the visualchars plugin so it displays shy like your patch.

**Comment by suit** [comment]
So the soft hyphen should be added via an external plugin then?

**Pull request closed without merging**
