### PR TITLE
TINY-11332: Upgrade dompurify for security vulnerability

### PR DESCRIPTION
**Pull request by jscasca**
Related Ticket: 

Description of Changes:
* Placeholder text

Pre-checks:
* [x] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [ ] Milestone set
* [ ] Docs ticket created (if applicable)

GitHub issues (if applicable):

### CODE REVIEW

**Comment by SvenLie** [comment]
Why is this PR closed? Will there be an update for the security vulerability?

**Comment by TheSpyder** [comment]
@SvenLie it was moved to #9895

**Comment by SvenLie** [comment]
Thank you. When can we expect that this PR is merged and released?

**Comment by TheSpyder** [comment]
It doesn't seem to be a critical vulnerability for TinyMCE, so rather than hold up the 7.4 release (due this week) it will go through proper QA and we expect it to be in 7.4.1 less than a week later.

**Pull request closed without merging**
