### PR TITLE
TINY-8985: Add Merge tag icon

### PR DESCRIPTION
**Pull request by noxuhax**
Related Ticket: TINY-8985

Description of Changes:
* Added `tag` icon for Merge tags feature into `oxide-icons-default` icon pack

Pre-checks:
* [x] ~Changelog entry added~
* [x] ~Tests have been added (if applicable)~
* [X] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set

### CODE REVIEW

**Comment by noxuhax** [comment]
Not sure if this PR requires it’s own changelog entry since this is a part of Merge tags feature.

**Review by lorenzo-pomili — APPROVED** [review]

**Comment by noxuhax** [comment]
> Should it be called `addtag` since it's a tag with a plus on it or is that over complicating things?

That might make sense. @vpyshnenko I remember discussing icon name on one of the checkins, what do you think about changing it?

**Comment by vpyshnenko** [comment]
I'm ok with changing icon name to `addtag`

**Review by TheSpyder — APPROVED** [review]
Don't forget to rename before merge

- [ ] rename to `addtag`

**Review by HAFRMO — APPROVED** [review]

**Pull request merged**
