### PR TITLE
Bind toolbar events to an editor's ui_container

### PR DESCRIPTION
**Pull request by Thomas-Richards-i-Nexus**
There is a bug in TinyMCE where if you create a new editor instance with the "ui_container" option, all previous instances behave as though they were given the same option.

This means that using "ui_container" doesn't fix the issue with colour-pickers and drop-downs becoming un-moored (https://github.com/tinymce/tinymce/issues/3592), if there are editors in different scrollable areas on a page.

By the looks of things this is not intentional because each editor has its own "ui_containter" property in addition to the shared "ui_container" environment variable. I've changed one place where the environment variable is used when I believe using the local container makes sense.

`grunt test` gives the same errors as master.
`grunt lint` passes.

### CODE REVIEW

**Comment by FBDeveloperAll** [comment]
Is this only a fix for the inlite theme? I have this issue with the modern theme as well.

**Comment by Thomas-Richards-i-Nexus** [comment]
> Is this only a fix for the inlite theme? I have this issue with the modern theme as well.

Looks like it.

I've just looked for scroll events being bound and there's some in: `src/themes/modern/main/ts/ui/ContextToolbars.ts`. I don't now how different each theme is, but you'd expect this behaviour to be defined consistently in a common place like `src/core/main/ts/init/Render.ts` maybe?

I'm unlikely to be given time to experiment with this, I'm afraid. Hopefully a TinyMCE employee will pick this up.

**Comment by TheSpyder** [comment]
Issues with the modern theme will have to be dealt with separately, I'm afraid.

`Env.container` looks like it was intended to be a fallback when the UI code did not have an instance variable set correctly. It's no longer used in TinyMCE 5.

A search of the code reveals `Env.container` is also used in `src/themes/inlite/main/ts/alien/UiContainer.ts` which may impact the UI as well. It looks easy to pass the editor setting in to that function, would you mind adding that to the PR?

**Comment by Thomas-Richards-i-Nexus** [comment]
(I force pushed to change the commit email then realised I had to change it back.)

**Comment by TheSpyder** [comment]
Apologies for not following up on this time. I think it was not long after this conversation that we decided in TinyMCE 5 the inlite theme would become a plugin, and we also stopped using `Env.container` (although it looks like we didn't remove it, oops).

If you still need this fix in TinyMCE 4 please make a new PR targeting the `4.x` branch.

**Pull request closed without merging**
