### PR TITLE
Fix Selectbox data undefined value in the onsubmit event

### PR DESCRIPTION
**Pull request by gnuletik**
You can test with this HTML :
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test example</title>
  </head>
  <body>
    <textarea>TinyMCE</textarea>
    <script src='tinymce/js/tinymce/tinymce.js'></script>
    <script>
tinymce.PluginManager.add('testExample', function(editor, url) {
  editor.addButton('testExample', {
    text: 'Test example',
    icon: false,
    onclick: function() {
      openWindow();
    }
  });

  function openWindow() {
    editor.windowManager.open({
      title: 'Test',
      body: [
	{type: 'selectbox', name: 'foo', label: 'Foo', options: ['1', '2', '3', '4'], value: '2'}
      ],
      onsubmit: function(e) {
	console.log(e.data);
      }
    });
  }

});
tinymce.init({
  selector:'textarea',
  plugins: 'testExample',
  toolbar: 'testExample'
});
    </script>
  </body>
</html>

```

You then have to click on the testExample button and then validate it. The data will be logged to the console.
Console log without the fix: `Object { foo: "" }  test.html:26:2`
Console log with the fix: `Object { foo: "1" }  test.html:26:2`

PS: I attempted to make an automated test as recommended in the readme.md but `grunt test` doesn't exist. The docs should be updated to explain how to implement tests.

### CODE REVIEW

**Comment by GNUletik** [comment]
It's now possible to send a value parameter to pre-fill the selectbox, I updated the example.

NB: The value parameter is not present in the documentation but it is working for the Textbox widget. Should it be added to the documentation ?

Thanks

**Comment by GNUletik** [comment]
Any news on this ?

**Comment by GNUletik** [comment]
?

**Comment by GNUletik** [comment]
Test of the bug here: http://fiddle.tinymce.com/bWfaab

Currently, when validating, the data always contains the `value` parameter given in parameter if provided. An empty value is present if the `value` parameter is not provided line 15.

With this fix, the `value` parameter fill the content and the user's choice is available in the e.data object in the onsubmit event.

**Comment by GNUletik** [comment]
@spocke @fyrkant Can you have a look at it guys ?

**Comment by GNUletik** [comment]
Just merged upstream into my fork.
Still not fixed: see https://github.com/tinymce/tinymce/pull/3598#issuecomment-317713126 to test.

**Comment by fyrkant** [comment]
Unsure if this is nevessary, as you can do this with a `listbox` instead right now, like this: http://fiddle.tinymce.com/bWfaab/1

**Comment by GNUletik** [comment]
@fyrkant That's true, same feature :)

**Comment by fyrkant** [comment]
The TinyMCE source code has been converted to TypeScript which makes this PR impossible to merge, so I am closing it. Please open up a new PR written in TypeScript if you want us to take a look at it again.

**Pull request closed without merging**
