### PR TITLE
Plugin to strip nbsp entities in unwanted places

### PR DESCRIPTION
**Pull request by ausi**
We are using tinyMCE in Contao and discovered an issue in webkit/blink-based browsers (Chrome, Safari, Opera,...) which often insert `&nbsp;` instead of single spaces. The related Contao ticket: contao/core#8566

I found two simple ways to reproduce the issue in a standard tinyMCE instance. Way 1:

1. Write the word `Lorem`
2. Link the word to `#`
3. Move the cursor at the end and press <kbd>SPACE</kbd>
4. Write the word `Ipsum`
5. Show source or save

Way 2:

1. Write the words `Lorem ipsum`
2. Mark the word `ipsum`
3. Overwrite it with `dolor`
4. Show source or save

In either case the resulting HTML code includes a `&nbsp;` entity instead of a single space character.

I created a plugin that should strip such unwanted `&nbsp;` entities while keeping them in places where they make sense like in `<p>&nbsp;</p>`. Because this affects all tinyMCEs we thought adding the plugin to tinyMCE itself could make sense and so I created this pull request. What do you think?

### CODE REVIEW

**Comment by hella-schu** [comment]
Thank you! I hope the pull request will be accepted.

**Comment by leofeyer** [comment]
@spocke Any update on this one?

**Comment by leofeyer** [comment]
@spocke The PR has been updated and uses the current API now. Please review.

**Comment by leofeyer** [comment]
This is now included in https://github.com/contao-components/tinymce4 by default.

**Comment by fyrkant** [comment]
@leofeyer thank you for this, nice work with the plugin and adding tests and everything, but I don't think this is something that should be added as a core plugin. If anyone wants the functionality they can add the few lines of code into their init code, or maybe you can make it into a third party plugin. Thank you again!

**Comment by leofeyer** [comment]
> If anyone wants the functionality they can add the few lines of code into their init code

How would those lines look like?

**Comment by donShakespeare** [comment]
I think he means it is a too specific feature?
And that users may use the solution in third party plugin or simply add the code in their init`setup`.

Emphasis on *too unique* ? (removes non-breaking space here but not there)
Maybe if this is ever accepted it won't be a plugin at all, but something more native in TinyMCE.

In MODX for example, we have an issue of the replaced ampersand, so we use a "plugin" in the init
```tinymce.init({
  selector: "#example",
  //protectAmpersand: false,
  setup: function(editor){ //place this part in your commonCode - avoid duplicates
    editor.on('SaveContent', function(ed) {
      if(editor.getParam("protectAmpersand", true)){ //allow editors to turn this off protectAmpersand: false,
        ed.content = ed.content.replace(/& amp;/g, '&'); //I preserved ampersand by spacing - please amend
      }
    });
  }
});```

**Comment by fyrkant** [comment]
@leofeyer I just mean that the plugin is so small that you can just copy in the code into the init `setup` function, exactly like @donShakespeare shows above.

**Comment by leofeyer** [comment]
I agree that the plugin is very small. And it probably would not be needed at all, if the &nbsp; bug gets fixed in TinyMCE directly.

@fyrkant Do you want us to create a PR that tries to fix this in the TinyMCE core?

By the way, this is not my plugin. It has been created by @ausi.

**Pull request closed without merging**
