### PR TITLE
Update Dialog.js

### PR DESCRIPTION
**Pull request by chaeller**
Fix missing call of the custom url converter in the image plugin #4064

### CODE REVIEW

**Comment by fyrkant** [comment]
This is not needed, the urlconverter is already run on src, see this fiddle for example:
http://fiddle.tinymce.com/hfgaab

**Comment by chaeller** [comment]
The example http://fiddle.tinymce.com/hfgaab shows, that the url converter is NOT called, if the OK button is clicked. The url converter is only called, if you press for example the tabulator key.

**Comment by fyrkant** [comment]
Ok, so it's only on change it is added, not on submit.

**Comment by fyrkant** [comment]
Hmm, now when I am trying it again I can't get it to fail. 

On the fiddle linked above i do this:
1. Click image button to open dialog
2. Enter "hello" into source
3. Press Ok button

If I open the source code viewer I get this:
```html
<p><img src="hello?added_stuff" alt="" /></p>
```

Seems to work?

**Comment by fyrkant** [comment]
The TinyMCE source code has been converted to TypeScript which makes this PR impossible to merge, so I am closing it. Please open up a new PR written in TypeScript if you want us to take a look at it again.

**Pull request closed without merging**
