### PR TITLE
TINY-10654: Remove deprecated template plugin

### PR DESCRIPTION
**Pull request by ltrouton**
Related Ticket: TINY-10654

Description of Changes:
* Remove the deprecated template plugin for the 7.0 release

NOTE: I did not remove the `template.svg` file as it is being used by the advemplate plugin

Pre-checks:
* [X] Changelog entry added
* [X] Tests have been added (if applicable)
* [X] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [X] Milestone set
* [X] Docs ticket created (if applicable)

GitHub issues (if applicable):

### CODE REVIEW

**Review by TheSpyder — APPROVED** [review]

**Review by MitchC1999 — APPROVED** [review]

**Comment by kemister85** [comment]
Would it be worth removing `template` plugin from these demos? @ltrouton 
- `tinymce-premium/ui/oxide-premium-skins/src/demo/material-outline.html`
- `tinymce-premium/ui/oxide-premium-skins/src/demo/material-classic.html`
- `tinymce-premium/ui/oxide-premium-skins/src/demo/jam.html`
- `tinymce-premium/ui/oxide-premium-skins/src/demo/fluent.html`
- `tinymce-premium/ui/oxide-premium-skins/src/demo/fabric.html`

**Comment by ltrouton** [comment]
> Would it be worth removing `template` plugin from these demos? @ltrouton
> 
> * `tinymce-premium/ui/oxide-premium-skins/src/demo/material-outline.html`
> * `tinymce-premium/ui/oxide-premium-skins/src/demo/material-classic.html`
> * `tinymce-premium/ui/oxide-premium-skins/src/demo/jam.html`
> * `tinymce-premium/ui/oxide-premium-skins/src/demo/fluent.html`
> * `tinymce-premium/ui/oxide-premium-skins/src/demo/fabric.html`

Thank @kemister85. I'll make the updates in my other PR

**Comment by NicolasCARPi** [comment]
Hello,

Given that the related issue is private, could you shed some light on the reason for deprecating this module? Will another module with similar functionality be present?

**Comment by TheSpyder** [comment]
@NicolasCARPi a new premium template plugin was released with TinyMCE 6.4, the open source plugin was deprecated at the same time.
https://www.tiny.cloud/tinymce/features/templates/
https://www.tiny.cloud/docs/tinymce/latest/advanced-templates/

**Comment by NicolasCARPi** [comment]
@TheSpyder I see, but couldn't they co-exist? A premium plugin with advanced features, and an open source one with less features, but still useful.

The links you posted don't give a reason for the deprecation of a functional plugin. Is it a commercial strategy to replace all open source plugins with a premium version? IMHO premium plugins are a great way to monetize the project, but it shouldn't be detrimental to the existing open source plugins. Removing a perfectly working plugin for no other reason that a paid improved version exists is a pity.

Thank you for your time.

**Comment by TheSpyder** [comment]
Maintaining the second plugin, even if we never added another feature to it, still has a cost. We don't want to pay that cost, but the MIT license allows the community to make a copy of the TinyMCE 6 version of the plugin and continue maintaining it if necessary (as long as credit is supplied following the license guidelines).

We are committed to open source development. In 6.5 we added a new open source plugin: https://www.tiny.cloud/docs/tinymce/latest/accordion/

**Comment by NicolasCARPi** [comment]
@TheSpyder Thank you for your answer. I understand fully this argument about maintenance cost, and I'm glad to see new open source plugins being implemented (I'm even a user of this one!).

Best regards,
~Nicolas

**Pull request merged**
