### PR TITLE
Added iframeTemplateCallback

### PR DESCRIPTION
**Pull request by Namstel**
Related Ticket:

Description of Changes:
* Adds the `iframeTemplateCallback` parameter to the `getIframeHtml` function

Pre-checks:
* [ ] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/` for new features (if applicable)

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

### CODE REVIEW

**Comment by metricjs** [comment]
Hi @Namstel, thanks for this PR. We are currently reviewing the feature, and will get back to you with any questions. However, for us to accept this PR, we would need you to sign the CLA. Could you please check your emails - including the Spam folder, just in case - for an email from us regarding the CLA. Let us know if you can't find it, and we will re-send the email.

**Comment by Namstel** [comment]
Hi @metricjs ,

That's odd, I signed it the same day. If I follow the link again, it says:
**There was an issue with signing you, you should probably contact us asap.**

Could you send me a new one?

I'll look into adding a CHANGELOG entry and tests ASAP.

**Comment by metricjs** [comment]
Hi @Namstel,

It appears your commits come from two different emails. You've signed for `namstel@...` but not for `niels@...`.  I've resent the CLA email for the latter. Hopefully you can guess the email addresses - I didn't want to put your full email on Github.

**Comment by metricjs** [comment]
Hey @Namstel, thanks for fixing the CLA issues! 

This feature has been accepted, so we are looking to merge this PR for an upcoming release. We may merge this into a feature branch first, rather than directly into develop, so that we can add tests and such. Unless you would like to attempt adding tests yourself?

**Comment by Namstel** [comment]
Hi @metricjs ,

Thanks. Go ahead and merge it into the feature branch. I'm afraid I've been swamped at work and I can't seem to find the time to do these thing myself.

**Pull request merged**
