### PR TITLE
Prevent setting dropdown to an empty value.

### PR DESCRIPTION
**Pull request by rgriffith**
Consistent with how the Font Family dropdown is set, only set the text if pt has a value.

**Before submitting a pull request** please do the following:

1. Fork [the repository](https://github.com/tinymce/tinymce) and create your branch from `master`
2. Have you added some code that should be tested? Write some tests! (Are you unsure how to write the test you want to write, ask us for help!)
3. Ensure that the tests pass: `grunt test`
4. Ensure that your code passes the linter: `grunt lint`
5. Make sure to sign the CLA.

### CODE REVIEW

**Comment by rgriffith** [comment]
Screenshot of the behavior we were seeing:

screen_shot_2017-09-29_at_9_37_54_am

Within an application of our's, we allow users to customize the editor's menubar/toolbar and in this interface we hide the body since it's not necessary. In Firefox, there is no body and thus the control's text is set to an empty value due to the fallback `pt` variable being empty at that point. The **Font Family** control is just fine because there is a check to make sure the fallback value is present before setting the text.

**Comment by fyrkant** [comment]
Can you create a [fiddle](http://fiddle.tinymce.com/) showing this problem? I can't reproduce it.

**Comment by rgriffith** [comment]
[Here is a pen](https://codepen.io/anon/pen/BwGavy) (using v4.5.7) that is a similar setup to what we were trying to do. I am seeing slightly different behavior here which is instead of an empty dropdown it's showing `[object Object]`, but a similar issue which is the dropdown should be showing "Font Size". 

I noticed those core selects were refactored a bit in 4.7.x and verified I was also able to reproduce the same behavior on both dev and stable.

I realize this is a bit of an edge case, but all selects should be handled the same which is to show the "placeholder".

The workaround we have for now is to hide the `.mce-edit-are` within `init_instance_callback` which is called after the select is initialized and gets a value based on the body content.

**Comment by rgriffith** [comment]
As I mentioned, this is definitely a bit of an edge case. Our application allows administrators to interact with a preview of the menubar/toolbar so they can configure what buttons are available to their end users, so there is no body shown in this case.

The reason I submitted this PR was so the Font Size select is consistent with the Font Family select and falls back to the placeholder if a value can not be found. [Here is an updated pen](https://codepen.io/anon/pen/qPQEoz) demonstrating this difference between the two.

**Comment by fyrkant** [comment]
The TinyMCE source code has been converted to TypeScript which makes this PR impossible to merge, so I am closing it. Please open up a new PR written in TypeScript if you want us to take a look at it again.

**Pull request closed without merging**
