### PR TITLE
Make endCommentRegexp sticky to fix parsing of comments with mismatching sequence

### PR DESCRIPTION
**Pull request by charsbar**
Related Ticket:

Description of Changes:
* Make endCommentRegexp sticky so that the parser doesn't look for a matching end-comment before the malformed comment

Pre-checks:
* [ ] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):
#6014

### CODE REVIEW

**Comment by metricjs** [comment]
Hey @charsbar, thanks for the contribution. However, unfortunately we can't accept it at this stage. TinyMCE supports IE11 and the sticky flag `y` is not supported on IE11. Would you like to make an attempt at fixing this in an IE11-compatible way? If not, we can log an internal ticket for this. 

We also need to check if this is what the spec recommends, and check that the solution does not introduce any vulnerabilities (e.g. mXSS) since it involves parsing and sanitising HTML. Do you happen to know what the recommended approach is for this kind of issue?

Out of curiosity, how did you hit this issue?

**Comment by charsbar** [comment]
Hi @metricjs, thanks for your comment. I changed the logic to see if ```lastIndex``` is actually increased, which should be IE11-compatible.

I found this when one of our customers sent us a report that one of their pages didn't work well with a newer version of TinyMCE we updated. The page happened to have several comments and the last one lacked the closing part.

**Comment by ashfordneil** [comment]
Hi charsbar,
Thanks for having another go at fixing this! We've reviewed this further and this still wouldn't fix the issue I'm afraid, as it doesn't handle the case where a match is found before the start index.
We've discussed 2 ways this could be fixed:
- Convert the regex to a global, so the lastIndex will be used
- Split the string using the start index and then add the index to the matched regex index.
Would you like to have another attempt at fixing this, or would you prefer us to finalise this?

**Comment by charsbar** [comment]
Hi @ashfordneil, thank you for reviewing. It seems you already have better solutions. I'd close this PR and ask you to finalize this.

**Pull request closed without merging**
