### PR TITLE
TINY-7854: Add bogus attribute to image resize backdrop

### PR DESCRIPTION
**Pull request by TheSpyder**
Related Ticket: TINY-7854

Description of Changes:
* Super minor fix, not critical at all.
* All of the image resize temporary elements include `data-mce-bogus=all`, except the backdrop. As a result the RTC mutation observer needs to include a special case for the backdrop element. This adds a small overhead to every document mutation.
* Adding this attribute is also more consistent with other elements used for resize.

Pre-checks:
* [x] Changelog entry added
* [x] ~Tests have been added (if applicable)~
* [x] Branch prefixed with `feature/` for new features (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):

### CODE REVIEW

**Review by ashfordneil — COMMENTED** [review]
Look good, but I don't really understand this area of the codebase enough to approve it

**Review by metricjs — APPROVED** [review]

**Review by spocke — APPROVED** [review]

**Comment by lnewson** [comment]
@TheSpyder which version did you want this to target? The Jira doesn't mention, but I'm guessing you'd prefer this to be in 5.9.2 rather than 5.10.0? If so we'll need to rebase this and target `master` instead of `develop`.

**Review by lnewson — APPROVED** [review]

**Comment by TheSpyder** [comment]
@lnewson it's not a critical fix, but it's also low risk enough that it would be nice to squeeze into 5.9.2.

We will have our draft PR waiting in the RTC codebase until it's merged :)

**Comment by lnewson** [comment]
Turns out we're likely not doing 5.9.2 now sorry, so ignore what I said above :cry:

**Review by HAFRMO — APPROVED** [review]

**Pull request merged**
