### PR TITLE
Adding an annotation plugin

### PR DESCRIPTION
**Pull request by chasnz**
This pull request adds an annotation tool to the plugins directory. The user highlights a word or phrase within the TinyMCE editor and clicks the annotation icon in the toolbar. A popup window allows the author to input text as the annotation. The annotated text will appear as a yellow highlight and can be edited by clicking anywhere within the highlight and clicking the annotation icon again.

The tool basically wraps the highlighted text in a SPAN tag and the annotation text is saved as an attribute of the SPAN tag, eg.

	<span class="annotation" data-annotation-value="Whatever you typed">The text that you highlighted</span>

On the public-facing website, the annotation can be read using jQuery, eg.

	var annotations = $(".annotation");
	annotations.each( function() {
		var annotationText = $(this).attr('data-annotation-value');
	});

To include the annotation icons within the TinyMCE toolbar you must add this code to the init function:

	// activate tinymce editor on the textarea with id="canvas".
	// Notice the addition of annotate and delete-annotation in the plugins and toolbar attributes.
	tinymce.init({
		selector: '#canvas',
		width : 1000,
		height:800,
		plugins: 'advlist autolink lists link image charmap print preview anchor searchreplace
			visualblocks code fullscreen insertdatetime media table contextmenu paste annotate',
		toolbar: "insertfile undo redo | styleselect | bold italic underline subscript superscript | 
			alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | 
			link unlink image table | annotate delete-annotation | code",
		content_css : 'css/style.css'
	});

Don't forget to add the following selector to your stylesheet, otherwise the annotated text won't have the yellow highlight.

	.annotation {
		background-color:#ff0;
	}

You can see a working demo at
[https://flexiblelearning.auckland.ac.nz/tinymcedemo/annotations/](https://flexiblelearning.auckland.ac.nz/tinymcedemo/annotations/)

### CODE REVIEW

**Comment by k644606347** [comment]
I feel this plugin functionality is too customized, it seems not suitable as a core plugin of Tinymce; more suitable for inclusion as an alternative plug-ins, such as CKeditor has a third-party plug-in list;
thanks in any case for your contribution :)

**Comment by chasnz** [comment]
Okay thanks for your feedback.I was wondering whether there was another
development project that featured ad-hoc plugins, so I'll take a look at
CKeditor. Can you think of any other websites that feature user-developed
plugins?

Kind regards
Craig.

**Comment by fyrkant** [comment]
The TinyMCE source code has been converted to TypeScript which makes this PR impossible to merge, so I am closing it. Please open up a new PR written in TypeScript if you want us to take a look at it again.

**Comment by WriterStat** [comment]
@chasnz I'd be interested in this as a third party plugin for tinymce it would need a popup interface for displaying comments and a php storage ability I think for full functionality. Best, -C

**Comment by chasnz** [comment]
I've updated the code and posted the tool here: https://github.com/chasnz/annotation-tool-for-tinymce-4
Note that there is no guarantee that it will work in versions higher than TinyMCE 4.6.1

**Pull request closed without merging**
