### PR TITLE
Update table styles with correct values, ref #4509

### PR DESCRIPTION
**Pull request by alexmaris**
Fix for issue #4509

### CODE REVIEW

**Comment by fyrkant** [comment]
While this fixes the problem with the border input not updating the border when you have `table_style_by_css` set to true, it also breaks the style input if you have the advanced tab activated so it won't update the border-width of the table when updating it in the style input.

**Comment by alexmaris** [comment]
@fyrkant I didn't see that as a breaking behavior, rather as a user I expect the an explicitly set border-width value will override what's in the Advanced Tab -> Style input. How do you expect it to work? Should the values between the two fields sync on chance?

**Comment by alexmaris** [comment]
@fyrkant any input on what the expected behavior should be when the border values in the basic tab conflict with those in the advanced tab?

**Comment by metricjs** [comment]
Thanks @alexmaris for this PR! Unfortunately we're no longer accepting non-critical fixes or features for TinyMCE 4 and after the end of year we'll no longer be providing support: https://www.tiny.cloud/blog/tinymce-4-support-window/. If this is an issue with TinyMCE 5 and you'd like to recreate this PR against TinyMCE 5, we'd be happy to review this fix.

**Pull request closed without merging**
