### PR TITLE
Render menu to root element if it is inside a dialog

### PR DESCRIPTION
**Pull request by seraph17**
Fixes: #4293 
Fixes: #4281

### CODE REVIEW

**Comment by alasvant** [comment]
Affected by the issues and would be great to get those fixed.

**Comment by ErikHen** [comment]
Would be great if this could be fixed shortly.
Thanks.

**Comment by fyrkant** [comment]
The first issue linked has been fixed, is this PR still needed?

**Comment by seraph17** [comment]
Yes, the first issue is fixed in another way.
But this PR might help when people using ui_container setting.

**Pull request closed without merging**
