### PR TITLE
TINY-9920: Add test to check fallback Keyboard Navigation html matches English html

### PR DESCRIPTION
**Pull request by mkzhx**
Related Ticket: TINY-9920

Description of Changes:
* Related to TINY-9633 PR https://github.com/tinymce/tinymce/pull/8764
* Update fallback html string to match the string loaded from en.html exactly (make newlines and spacing consistent)
* Add test to check fallback html string matches string loaded from en.html exactly

Pre-checks:
* [x] ~Changelog entry added~
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] ~Docs ticket created (if applicable)~

GitHub issues (if applicable):

### CODE REVIEW

**Review by TheSpyder — COMMENTED** [review]
I posted this in the earlier PR but apparently github sucks on mobile and it left my comment as pending when I submitted my approval.

I don’t think we need the fallback 🤔 yes it can technically fail but much like the emoji database on the emoticons plugin it’s a critical piece and the dialog just won’t work without it.

I would rather not have the string in the codebase twice, even with tests to verify, apologies for needing to do all this work unnecessarily

**Comment by mkzhx** [comment]
> I posted this in the earlier PR but apparently github sucks on mobile and it left my comment as pending when I submitted my approval.
> 
> I don’t think we need the fallback 🤔 yes it can technically fail but much like the emoji database on the emoticons plugin it’s a critical piece and the dialog just won’t work without it.
> 
> I would rather not have the string in the codebase twice, even with tests to verify, apologies for needing to do all this work unnecessarily

@TheSpyder We would need the fallback for the situation where an invalid language code is specified in the `language` option, since we rely on a valid language code to retrieve the corresponding HTML file.

**Comment by TheSpyder** [comment]
I didn't think of that, but I like the idea of hard-coding `en.html` in the plugin as the fallback.

**Comment by mkzhx** [comment]
Closed to implement loading from `en.html` as a fallback in TINY-9928.

**Pull request closed without merging**
